use_frameworks!
install! 'cocoapods', :share_schemes_for_development_pods => true
project 'Pippin.xcodeproj'
workspace 'Pippin.xcworkspace'

abstract_target 'PippinPods-iOS' do
    pod 'PippinCore', :path => '../..'
    pod 'PippinAdapters', :path => '../..'
    pod 'PippinLibrary', :path => '../..', :testspecs => ['Tests']

    # add nondefault adapters
    [
      'CoreLocation',
      'FormController',
      'CRUDViewController',
      'AVCaptureDevice',
      'InfoViewController',
      'CoreData',
    ].each do |subspec|
      pod "PippinAdapters/#{subspec}", :path => '../..'
    end

    # only link debugging podspec to debug configuration
    pod 'PippinDebugging', :path => '../..', :configurations => ['Debug']

    target 'Pippin-iOS' do
        platform :ios, '15.6'
    end
end

abstract_target 'PippinPods-macOS' do
    pod 'PippinLibrary', path: '../..'

    target 'Pippin-macOS' do
        platform :osx, '12.4'
    end
end

abstract_target 'PippinTestPods-iOS' do
  platform :ios, '15.6'
  pod 'PippinTesting', path: '../..', :testspecs => ['Tests']
  pod 'PippinLibrary', path: '../..'

  target 'PippinUITests-iOS'
  target 'PippinUnitTests-iOS'
end

post_install do | installer |
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
