language: objective-c
osx_image: xcode8.3
script: 
    - rake test
notifications:
    email:
        recipients:
         - andrew+travis+shared-utils@tworingsoft.com
        on_success: change
        on_failure: always
