language: objective-c
osx_image: xcode10
install:
  - bundle
  - bundle exec rake init
script: 
  - bundle exec rake test
notifications:
  email:
    recipients:
      - andrew+travis+Pippin@tworingsoft.com
    on_success: change
    on_failure: always
