language: objective-c
osx_image: xcode 8.2
script: 
    - xcodebuild -project shared-utils-tests/shared-utils-tests.xcodeproj -scheme shared-utils-ios -configuration Release analyze test
notifications:
    email:
        recipients:
         - andrew@tworingsoft.com
        on_success: change
        on_failure: always
