language: objective-c
osx_image: xcode10
install:
  - gem install cocoapods
  - rake init
script: 
  - rake test
notifications:
  email:
    recipients:
      - andrew+travis+Pippin@tworingsoft.com
    on_success: change
    on_failure: always
