language: objective-c
osx_image: xcode 8.2
script: 
    - rake test_travis
notifications:
    email:
        recipients:
         - andrew+travis+shared-utils@tworingsoft.com
        on_success: change
        on_failure: always
