use_frameworks!
install! 'cocoapods', :share_schemes_for_development_pods => true
platform :{{PLATFORM}}, '{{SDK_VERSION}}'

target '{{TARGET_NAME}}' do
  pod 'PippinAdapters/{{SUBSPEC}}', path: '../../../..'
  pod 'Crashlytics'
end
