use_frameworks!
install! 'cocoapods', :share_schemes_for_development_pods => true
platform :{{PLATFORM}}, '{{SDK_VERSION}}'

target '{{TARGET_NAME}}' do
  pod 'Pippin', path: '../../../..'
  pod '{{PODSPEC}}', path: '../../../..'
  pod 'Crashlytics'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            
            # manually set the SWIFT_VERSION value for pods that don't correctly specify it in their podspecs
            if target.name == 'PinpointKit' or target.name == 'Anchorage' then
                config.build_settings['SWIFT_VERSION'] = '4.2'
            elsif target.name == 'SwiftMessages' then
                config.build_settings['SWIFT_VERSION'] = '4'
            end
            
        end
    end
end
